[build]
  base = "client"
  command = "CI=false npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.herokuapp.com"
  REACT_APP_SOCKET_URL = "https://your-backend-url.herokuapp.com"
  CI = "false"
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 