[build]
  base = "client"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://chatbot-mk-api.onrender.com"
  REACT_APP_SOCKET_URL = "https://chatbot-mk-api.onrender.com"
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 